### ISSUE TITLE
Pegs a core at 100%

### ISSUE THREAD

**Issue by blubskye** [GenZmeY/KF2-AntiDDoS#1]
When I run the program like so:
tail /path/to/kf2/logs/Launch.log | ./kf2-antiddos-linux-amd64 /bin/bash ./deny.sh ./allow.sh

It says success then it pegs 1 of my cpu cores at 100% is this normal behavior?

**Comment by GenZmeY** [comment]
In your case, this should not work at all, since tail will only give the last 10 lines of the log once and that's it. You need to use at least `tail -f`, or even better, redirect the server's output to antiddos through a pipe directly

100% CPU usage can be if you give the program an already existing large log, but when working in real time, such a load should not be

In my case, antiddos serves about 30 kf2 servers and the load rarely exceeds 2%:
![image](https://user-images.githubusercontent.com/24222426/170497624-63737c32-71cc-41f2-a94e-95f2e8177a1c.png)

check it again. if you still have a problem i will try to help

**Comment by blubskye** [comment]
tail -f fixed the high cpu usage so thank you ^_^
