### ISSUE TITLE
Getting ddos'd but script isn't doing much

### ISSUE THREAD

**Issue by blubskye** [GenZmeY/KF2-AntiDDoS#2]
Still getting a ton of connections, yes I did modify your allow and deny to add about 20 to each side of the ports so it'd cover both servers. But from what I can see the connections are coming from random ports? 
![image](https://user-images.githubusercontent.com/31782440/178208749-3bdf95b2-8e75-4c93-8a34-5c57afd96a1f.png)

**Comment by GenZmeY** [comment]
It looks like what I wrote in the README is not enough... ok, I'll go into more detail

Incoming connections from random ports is normal - this is how connections work

You will continue to see spam logs for a while after the IP is banned - and that's okay too. This does not mean at all that the IP was not blocked (you can try to block yourself with a script and immediately enter the game - you will not be able to enter. That is, blocking works)

You see, there is a significant amount of time (seconds) between receiving a packet and reporting it in the log. Even if you just blocked the IP, the game has already received a bunch of new packets during this time and is processing them right now. And of course it will write about it in the log when it finishes (and it does not matter what you blocked there, the game does not even know about it).
Therefore, you will continue to receive OpenTheWorldBlaBlaBla messages from a previously blocked address for some time.

We cannot completely eliminate spam, but we can greatly reduce its amount. Roughly speaking, without antiddos you get 15000 packets and your server dies under load, with Antiddos you get 500 spam packets but your server is able to handle it and not crash. That's exactly how it works. You can test and compare yourself (with and without protection) if you have any doubts.

You can slightly reduce the delay between the start of spam and IP blocking if you replace reading the file (tail -f) with redirecting the server's output to antiddos (via pipe **|**) - in this case, there will be no time wasted writing and reading from disk.

But even so, it will not be possible to remove all spam - because there will still be a delay between receiving the packet and outputting it to the log.

There can be no perfect solution here for two reasons:
1. It is impossible to block all such packets even before they enter the game - among them there may be requests from real players, and in order to understand that this is a real player, we must let the game process this packet, i.e. skip it to the game.
2. It would be most effective to make DDoS protection in the network code of the game, but Tripware will never open the source (and they are not going to do protection either)

Therefore, we are forced to parse the log (with all the shortcomings of this method). But even in this form, it is much better than a cron script with a response time of 9 minutes. Here the reaction is calculated in seconds.

P.S.: if you are interested in real blocking statistics, see the output of antiddos. so you will see blocking in real time

P.S.S.: If you think this thing doesn't work, don't use it. I'm not going to convince you. I did this for myself in my free time and it keeps giving me results (my servers don't crash anymore and ping doesn't go up under ddos) and I'm fine with it. I'm not so worried that some of the spam gets through, the main thing is that it doesn't affect the game

**Comment by blubskye** [comment]
Never said it wasn't working, was just seeing the spam. And now my VPS I can't even access. What I find funny it's supposed to have DDOS protection built in. My guess is that I chose the wrong distro to use, I guess most people are using fedora or something, so I'm going to try that. I am just confused, frustrated because I just want to host servers so people can have fun! >_<

Is it possible to modify the script so it blocks them on all ports?

**Comment by GenZmeY** [comment]
> And now my VPS I can't even access

omg O_o why?

> What I find funny it's supposed to have DDOS protection built in.  

if your hoster says that it has DDoS protection, then I strongly doubt that it is universal (this is impossible). Most likely it is for some common and well-studied things like http/https traffic

> Is it possible to modify the script so it blocks them on all ports?

certainly. your script - your rules
I'm using centos8, so if you look at my example script from the README you'll see the following:
_firewall-cmd --add-rich-rule="rule family=ipv4 source address=$1_ **port port=7777-7815** _protocol=udp reject"_

that is, I block all traffic from the specified IP to the range of ports 7777-7815
if I remove the ports from this command, then I will block all traffic from this IP.

Judging by your screenshot, you have arch, I have not worked with it, so I can not say exactly how to change your script. Refer to the firewall documentation in archlinux.

I added ports to the rule so that the server does not block something important. If you read that thread on the tripware forum, then you probably remember that the attacker uses [ip spoofing](https://en.wikipedia.org/wiki/IP_address_spoofing). Imagine what happens if you receive spam from your home computer address and you block all traffic from this IP... or from your DNS server address...

So I don't think blocking traffic on all ports is a good idea...

**Comment by mastervash** [comment]
> What I find funny it's supposed to have DDOS protection built in. My guess is that I chose the wrong distro to use, I guess most people are using fedora or something, so I'm going to try that. 

I can all but guarantee you, that it's not your choice of distro that's at fault here. The "protection" hosts use happens completely on Network, meaning that the problem should be resolved before it even reaches your server. 

The actual problem is that server Hosts almost universally either exaggerate their DDoS mitigation capabilities in their marketing... or in dire cases, as has happened to me on 2 separate occasions over the past year, outright lie about having it. It's not always for malicious reasons either, it could just be because one hand doesn't have a clue what the other hand is promising customers.
