### ISSUE TITLE
Can i ask something?

### ISSUE THREAD

**Issue by iFanpSGTS** [GenZmeY/KF2-AntiDDoS#3]
How is the real DDoS Protection is really working?
Please explain me sir.

**Comment by GenZmeY** [comment]
How exactly this thing works is written README here:
https://github.com/GenZmeY/KF2-AntiDDoS#how-it-works
quite simple, because it was created to solve a [specific problem](https://forums.tripwireinteractive.com/index.php?threads/kf2-server-on-centos-linux-ddos-defense-with-the-help-of-firewalld.2337631/) here and now

I don’t know what you mean by “real DDoS Protection”, if these are some other systems, then you better ask their authors

**Comment by iFanpSGTS** [comment]
KF2 AntiDDoS is for game server? or website?

**Comment by GenZmeY** [comment]
For game server (Killing Floor 2)

**Comment by iFanpSGTS** [comment]
what is the different about website antiddos sir?

**Comment by GenZmeY** [comment]
Website traffic is different. The way to determine the real user is different

Probably you wanted to read something more specific and detailed here, but I will not waste time on this

I don't understand why you're asking me these off-topic questions. If this is what you are interested in - you have Google and the entire Internet
